/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "EnvelopeModule"
 * 	found in "Envelope.asn1"
 */

#include <asn_internal.h>

#include "Envelope.h"

static int
code_9_constraint(asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	/* Replace with underlying type checker */
	td->check_constraints = asn_DEF_ENUMERATED.check_constraints;
	return td->check_constraints(td, sptr, ctfailcb, app_key);
}

/*
 * This type is implemented using ENUMERATED,
 * so here we adjust the DEF accordingly.
 */
static void
code_9_inherit_TYPE_descriptor(asn_TYPE_descriptor_t *td) {
	td->free_struct    = asn_DEF_ENUMERATED.free_struct;
	td->print_struct   = asn_DEF_ENUMERATED.print_struct;
	td->ber_decoder    = asn_DEF_ENUMERATED.ber_decoder;
	td->der_encoder    = asn_DEF_ENUMERATED.der_encoder;
	td->xer_decoder    = asn_DEF_ENUMERATED.xer_decoder;
	td->xer_encoder    = asn_DEF_ENUMERATED.xer_encoder;
	td->uper_decoder   = asn_DEF_ENUMERATED.uper_decoder;
	td->uper_encoder   = asn_DEF_ENUMERATED.uper_encoder;
	if(!td->per_constraints)
		td->per_constraints = asn_DEF_ENUMERATED.per_constraints;
	td->elements       = asn_DEF_ENUMERATED.elements;
	td->elements_count = asn_DEF_ENUMERATED.elements_count;
     /* td->specifics      = asn_DEF_ENUMERATED.specifics;	// Defined explicitly */
}

static void
code_9_free(asn_TYPE_descriptor_t *td,
		void *struct_ptr, int contents_only) {
	code_9_inherit_TYPE_descriptor(td);
	td->free_struct(td, struct_ptr, contents_only);
}

static int
code_9_print(asn_TYPE_descriptor_t *td, const void *struct_ptr,
		int ilevel, asn_app_consume_bytes_f *cb, void *app_key) {
	code_9_inherit_TYPE_descriptor(td);
	return td->print_struct(td, struct_ptr, ilevel, cb, app_key);
}

static asn_dec_rval_t
code_9_decode_ber(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const void *bufptr, size_t size, int tag_mode) {
	code_9_inherit_TYPE_descriptor(td);
	return td->ber_decoder(opt_codec_ctx, td, structure, bufptr, size, tag_mode);
}

static asn_enc_rval_t
code_9_encode_der(asn_TYPE_descriptor_t *td,
		void *structure, int tag_mode, ber_tlv_tag_t tag,
		asn_app_consume_bytes_f *cb, void *app_key) {
	code_9_inherit_TYPE_descriptor(td);
	return td->der_encoder(td, structure, tag_mode, tag, cb, app_key);
}

static asn_dec_rval_t
code_9_decode_xer(asn_codec_ctx_t *opt_codec_ctx, asn_TYPE_descriptor_t *td,
		void **structure, const char *opt_mname, const void *bufptr, size_t size) {
	code_9_inherit_TYPE_descriptor(td);
	return td->xer_decoder(opt_codec_ctx, td, structure, opt_mname, bufptr, size);
}

static asn_enc_rval_t
code_9_encode_xer(asn_TYPE_descriptor_t *td, void *structure,
		int ilevel, enum xer_encoder_flags_e flags,
		asn_app_consume_bytes_f *cb, void *app_key) {
	code_9_inherit_TYPE_descriptor(td);
	return td->xer_encoder(td, structure, ilevel, flags, cb, app_key);
}

static asn_TYPE_member_t asn_MBR_header_2[] = {
	{ ATF_POINTER, 1, offsetof(struct header, block),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"block"
		},
};
static ber_tlv_tag_t asn_DEF_header_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_header_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* block at 7 */
};
static asn_SEQUENCE_specifics_t asn_SPC_header_specs_2 = {
	sizeof(struct header),
	offsetof(struct header, _asn_ctx),
	asn_MAP_header_tag2el_2,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_header_2 = {
	"header",
	"header",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_header_tags_2,
	sizeof(asn_DEF_header_tags_2)
		/sizeof(asn_DEF_header_tags_2[0]) - 1, /* 1 */
	asn_DEF_header_tags_2,	/* Same as above */
	sizeof(asn_DEF_header_tags_2)
		/sizeof(asn_DEF_header_tags_2[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_header_2,
	1,	/* Elements count */
	&asn_SPC_header_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_body_5[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct body, type),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_VisibleString,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"type"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct body, data),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"data"
		},
};
static ber_tlv_tag_t asn_DEF_body_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_body_tag2el_5[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* type at 12 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* data at 13 */
};
static asn_SEQUENCE_specifics_t asn_SPC_body_specs_5 = {
	sizeof(struct body),
	offsetof(struct body, _asn_ctx),
	asn_MAP_body_tag2el_5,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_body_5 = {
	"body",
	"body",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_body_tags_5,
	sizeof(asn_DEF_body_tags_5)
		/sizeof(asn_DEF_body_tags_5[0]) - 1, /* 1 */
	asn_DEF_body_tags_5,	/* Same as above */
	sizeof(asn_DEF_body_tags_5)
		/sizeof(asn_DEF_body_tags_5[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_body_5,
	2,	/* Elements count */
	&asn_SPC_body_specs_5	/* Additional specs */
};

static asn_INTEGER_enum_map_t asn_MAP_code_value2enum_9[] = {
	{ 0,	6,	"sender" },
	{ 1,	8,	"receiver" }
};
static unsigned int asn_MAP_code_enum2value_9[] = {
	1,	/* receiver(1) */
	0	/* sender(0) */
};
static asn_INTEGER_specifics_t asn_SPC_code_specs_9 = {
	asn_MAP_code_value2enum_9,	/* "tag" => N; sorted by tag */
	asn_MAP_code_enum2value_9,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1	/* Strict enumeration */
};
static ber_tlv_tag_t asn_DEF_code_tags_9[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_code_9 = {
	"code",
	"code",
	code_9_free,
	code_9_print,
	code_9_constraint,
	code_9_decode_ber,
	code_9_encode_der,
	code_9_decode_xer,
	code_9_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_code_tags_9,
	sizeof(asn_DEF_code_tags_9)
		/sizeof(asn_DEF_code_tags_9[0]) - 1, /* 1 */
	asn_DEF_code_tags_9,	/* Same as above */
	sizeof(asn_DEF_code_tags_9)
		/sizeof(asn_DEF_code_tags_9[0]), /* 2 */
	0,	/* No PER visible constraints */
	0, 0,	/* Defined elsewhere */
	&asn_SPC_code_specs_9	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_fault_8[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct fault, code),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_code_9,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"code"
		},
	{ ATF_POINTER, 1, offsetof(struct fault, reason),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UTF8String,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"reason"
		},
};
static ber_tlv_tag_t asn_DEF_fault_tags_8[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_fault_tag2el_8[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* code at 17 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* reason at 21 */
};
static asn_SEQUENCE_specifics_t asn_SPC_fault_specs_8 = {
	sizeof(struct fault),
	offsetof(struct fault, _asn_ctx),
	asn_MAP_fault_tag2el_8,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_fault_8 = {
	"fault",
	"fault",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_fault_tags_8,
	sizeof(asn_DEF_fault_tags_8)
		/sizeof(asn_DEF_fault_tags_8[0]) - 1, /* 1 */
	asn_DEF_fault_tags_8,	/* Same as above */
	sizeof(asn_DEF_fault_tags_8)
		/sizeof(asn_DEF_fault_tags_8[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_fault_8,
	2,	/* Elements count */
	&asn_SPC_fault_specs_8	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_body_or_fault_4[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct body_or_fault, choice.body),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_body_5,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"body"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct body_or_fault, choice.fault),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_fault_8,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"fault"
		},
};
static asn_TYPE_tag2member_t asn_MAP_body_or_fault_tag2el_4[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* body at 12 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* fault at 19 */
};
static asn_CHOICE_specifics_t asn_SPC_body_or_fault_specs_4 = {
	sizeof(struct body_or_fault),
	offsetof(struct body_or_fault, _asn_ctx),
	offsetof(struct body_or_fault, present),
	sizeof(((struct body_or_fault *)0)->present),
	asn_MAP_body_or_fault_tag2el_4,
	2,	/* Count of tags in the map */
	0,
	-1	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_body_or_fault_4 = {
	"body-or-fault",
	"body-or-fault",
	CHOICE_free,
	CHOICE_print,
	CHOICE_constraint,
	CHOICE_decode_ber,
	CHOICE_encode_der,
	CHOICE_decode_xer,
	CHOICE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	CHOICE_outmost_tag,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	0,	/* No PER visible constraints */
	asn_MBR_body_or_fault_4,
	2,	/* Elements count */
	&asn_SPC_body_or_fault_specs_4	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_Envelope_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Envelope, header),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_header_2,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"header"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Envelope, body_or_fault),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_body_or_fault_4,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"body-or-fault"
		},
};
static ber_tlv_tag_t asn_DEF_Envelope_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_Envelope_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* header at 7 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* body-or-fault at 14 */
};
static asn_SEQUENCE_specifics_t asn_SPC_Envelope_specs_1 = {
	sizeof(struct Envelope),
	offsetof(struct Envelope, _asn_ctx),
	asn_MAP_Envelope_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Envelope = {
	"Envelope",
	"Envelope",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Envelope_tags_1,
	sizeof(asn_DEF_Envelope_tags_1)
		/sizeof(asn_DEF_Envelope_tags_1[0]), /* 1 */
	asn_DEF_Envelope_tags_1,	/* Same as above */
	sizeof(asn_DEF_Envelope_tags_1)
		/sizeof(asn_DEF_Envelope_tags_1[0]), /* 1 */
	0,	/* No PER visible constraints */
	asn_MBR_Envelope_1,
	2,	/* Elements count */
	&asn_SPC_Envelope_specs_1	/* Additional specs */
};

