/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "TestModule"
 * 	found in "Test.asn1"
 */

#ifndef	_TestInput_H_
#define	_TestInput_H_


#include <asn_application.h>

/* Including external dependencies */
#include <INTEGER.h>
#include <UTF8String.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TestInput */
typedef struct TestInput {
	INTEGER_t	 number;
	UTF8String_t	 text;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TestInput_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TestInput;

#ifdef __cplusplus
}
#endif

#endif	/* _TestInput_H_ */
