/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "TestModule"
 * 	found in "Test.asn1"
 */

#ifndef	_TestOutput_H_
#define	_TestOutput_H_


#include <asn_application.h>

/* Including external dependencies */
#include <UTF8String.h>
#include <INTEGER.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TestOutput */
typedef struct TestOutput {
	UTF8String_t	 result;
	INTEGER_t	 code;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TestOutput_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TestOutput;

#ifdef __cplusplus
}
#endif

#endif	/* _TestOutput_H_ */
