/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "TestModule"
 * 	found in "Test.asn1"
 */

#ifndef	_TestOperation_H_
#define	_TestOperation_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TestInput.h"
#include "TestOutput.h"
#include <constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum TestOperation_PR {
	TestOperation_PR_NOTHING,	/* No components present */
	TestOperation_PR_input,
	TestOperation_PR_output
} TestOperation_PR;

/* TestOperation */
typedef struct TestOperation {
	TestOperation_PR present;
	union TestOperation_u {
		TestInput_t	 input;
		TestOutput_t	 output;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TestOperation_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TestOperation;

#ifdef __cplusplus
}
#endif

#endif	/* _TestOperation_H_ */
